--- 
- 
  become: true
  gather_facts: false
  hosts: all
  tasks: 
    - 
      apt_key: "url=http://pkg.jenkins-ci.org/debian/jenkins-ci.org.key state=present"
      become: true
      name: "ensure the jenkins apt repository key is installed"
    - 
      apt_repository: "repo='deb http://pkg.jenkins-ci.org/debian binary/' state=present update_cache=yes"
      become: true
      name: "ensure the repository is configured"
    - 
      name: "ensure jenkins is running"
      service: "name=jenkins state=started"
