--- 
- 
  become: true
  gather_facts: false
  hosts: all
  tasks: 
    - 
      apt: "pkg=maven state=latest update_cache=yes cache_valid_time=3600"
      become: true
      name: "install maven on your local Ubuntu machine"
