--- 
- 
  become: true
  hosts: all
  tasks: 
    - 
      apt: "name=aptitude state=latest update_cache=yes force_apt_get=yes"
      name: "Install aptitude using apt"
    - 
      apt: "name={{ item }} state=latest update_cache=yes"
      loop: 
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - python3-pip
        - virtualenv
        - python3-setuptools
      name: "Install required system packages"
    - 
      apt_key: 
        state: present
        url: "https://download.docker.com/linux/ubuntu/gpg"
      name: "Add Docker GPG apt Key"
    - 
      apt_repository: 
        repo: "deb https://download.docker.com/linux/ubuntu bionic stable"
        state: present
      name: "Add Docker Repository"
    - 
      apt: "update_cache=yes name=docker-ce state=latest"
      name: "Update apt and install docker-ce"
    - 
      apt: 
        name: python3-pip
        state: present
        update_cache: true
      name: "Install pip"
    - 
      name: "Install Docker Module for Python"
      pip: 
        name: docker
    - 
      docker_image: 
        name: "{{ container_image }}"
        source: pull
      name: "Pull default Docker image"
    - 
      docker_container: 
        command: "{{ container_command }}"
        image: "{{ container_image }}"
        name: "{{ container_name }}{{ item }}"
        state: present
      name: "Create default containers"
      with_sequence: "count={{ containers }}"
  vars_files: 
    - vars/default.yml
